sudo: required
services:
  - docker
before_install:
  - docker build -t rykuno/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run rykuno/react-test npm run test -- --coverage

after_success: 
  - docker build -t rykuno/multi-client ./client
  - docker build -t rykuno/multi-nginx ./nginx
  - docker build -t rykuno/multi-server ./server
  - docker build -t rykuno/multi-worker ./worker
